name: tower_of_hanoi
description: tower of hanoi on flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  material_design_icons_flutter:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - logo.png